### ISSUE TITLE
HTTP ERROR 410 Gone

### ISSUE THREAD

**Issue by hintoz** [fastlane/boarding#244]
Hello, since yesterday Apple returns error 410 when accessing form boarding on path /v2/providers/1111111/apps/2222222222/groups

```
2019-04-05T11:47:37.149619+00:00 app[web.1]: [4] ! Unable to load application: Spaceship::UnexpectedResponse: <html>
2019-04-05T11:47:37.149645+00:00 app[web.1]: <head>
2019-04-05T11:47:37.149647+00:00 app[web.1]: <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
2019-04-05T11:47:37.149649+00:00 app[web.1]: <title>Error 410 Gone</title>
2019-04-05T11:47:37.149650+00:00 app[web.1]: </head>
2019-04-05T11:47:37.149652+00:00 app[web.1]: <body><h2>HTTP ERROR 410</h2>
2019-04-05T11:47:37.149653+00:00 app[web.1]: <p>Problem accessing /v2/providers/1111111111/apps/2222222222/groups. Reason:
2019-04-05T11:47:37.149655+00:00 app[web.1]: <pre>    Gone</pre></p>
2019-04-05T11:47:37.149656+00:00 app[web.1]: </body>
2019-04-05T11:47:37.149657+00:00 app[web.1]: </html>
2019-04-05T11:47:37.149719+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.4.0/bin/puma)
2019-04-05T11:47:37.149795+00:00 app[web.1]: Spaceship::UnexpectedResponse: <html>
2019-04-05T11:47:37.149797+00:00 app[web.1]: <head>
2019-04-05T11:47:37.149799+00:00 app[web.1]: <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
2019-04-05T11:47:37.149800+00:00 app[web.1]: <title>Error 410 Gone</title>
2019-04-05T11:47:37.149801+00:00 app[web.1]: </head>
2019-04-05T11:47:37.149803+00:00 app[web.1]: <body><h2>HTTP ERROR 410</h2>
2019-04-05T11:47:37.149804+00:00 app[web.1]: <p>Problem accessing /v2/providers/111111111/apps/222222222222/groups. Reason:
2019-04-05T11:47:37.149806+00:00 app[web.1]: <pre>    Gone</pre></p>
2019-04-05T11:47:37.149807+00:00 app[web.1]: </body>
2019-04-05T11:47:37.149808+00:00 app[web.1]: </html>
```

**Comment by janpio** [comment]
Yes, see https://github.com/fastlane/fastlane/issues/14521 for the main issue tracking this.

**Comment by clippka** [comment]
I have the same issue. Since https://github.com/fastlane/fastlane/issues/14521 is fixed now I updated my heroku git repository from latest upstream and tried to push. Precompilation of assets during push already failed with 410 gone?

https://github.com/fastlane/fastlane/issues/14521

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/issues/14521 didn't fix nearly all cases of brokenness unfortunately.

**Comment by joshdholtz** [comment]
Got a PR up for fixing this ^^ 💪

**Comment by clippka** [comment]
I verified that the pr from @joshdholtz fixes this issue for me. Thanks!
