### ISSUE TITLE
Not working - including your example!

### ISSUE THREAD

**Issue by fremontmj** [fastlane/boarding#9]
I tried to run my copy of boarding (which I installed a week ago, and it worked then) on heroku, and got:

"Something went wrong"

I then tried your example installation and the same thing happened.

Here's the log from my installation:

```
2015-08-14T19:36:14.415804+00:00 heroku[web.1]: Unidling
2015-08-14T19:36:14.416220+00:00 heroku[web.1]: State changed from down to starting
2015-08-14T19:36:18.372892+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 36205 -e production`
2015-08-14T19:36:24.459038+00:00 app[web.1]: [2015-08-14 19:36:24] INFO  ruby 2.0.0 (2015-04-13) [x86_64-linux]
2015-08-14T19:36:24.458943+00:00 app[web.1]: [2015-08-14 19:36:24] INFO  WEBrick 1.3.1
2015-08-14T19:36:24.459592+00:00 app[web.1]: [2015-08-14 19:36:24] INFO  WEBrick::HTTPServer#start: pid=3 port=36205
2015-08-14T19:36:25.016358+00:00 heroku[web.1]: State changed from starting to up
2015-08-14T19:36:27.209969+00:00 heroku[router]: at=info method=GET path="/?token=(removed)" host=intense-forest-3864.herokuapp.com request_id=67e986a7-0d6b-47b5-b518-5f212cdf8412 fwd="173.11.115.138" dyno=web.1 connect=0ms service=675ms status=500 bytes=1754
2015-08-14T19:36:27.893753+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=intense-forest-3864.herokuapp.com request_id=a92052c4-59d8-46f3-a673-7cf0917469f8 fwd="173.11.115.138" dyno=web.1 connect=0ms service=6ms status=200 bytes=228
2015-08-14T19:36:40.070091+00:00 heroku[router]: at=info method=GET path="/?token=(removed)" host=intense-forest-3864.herokuapp.com request_id=ff0cffee-2632-4f6b-829c-626cf20b21fb fwd="173.11.115.138" dyno=web.1 connect=0ms service=423ms status=500 bytes=1754
2015-08-14T19:38:59.293794+00:00 heroku[router]: at=info method=GET path="/" host=intense-forest-3864.herokuapp.com request_id=aedca6c7-255c-41d1-9a85-8bf1ba6cc29d fwd="173.11.115.138" dyno=web.1 connect=1ms service=517ms status=500 bytes=1754
2015-08-14T19:46:51.926260+00:00 heroku[router]: at=info method=GET path="/" host=intense-forest-3864.herokuapp.com request_id=de48de70-e76f-45fb-b06a-9a3206550197 fwd="173.11.115.138" dyno=web.1 connect=7ms service=527ms status=500 bytes=1754
2015-08-14T19:46:52.780666+00:00 heroku[router]: at=info method=GET path="/" host=intense-forest-3864.herokuapp.com request_id=cc15d177-73cb-4878-a89c-b1e87760ed94 fwd="173.11.115.138" dyno=web.1 connect=4ms service=398ms status=500 bytes=1754

:(
```

**Comment by fremontmj** [comment]
PS Cool tools, thanks!

**Comment by KrauseFx** [comment]
I just pushed an update, could you try again?

**Comment by fremontmj** [comment]
Did you happen to update the live example?  It still doesn't work...

https://boarding.herokuapp.com/

**Comment by KrauseFx** [comment]
Sorry about this, working on a fix :+1:

**Comment by rlimberger** [comment]
We are also running into this. Just wanted to add myself to the thread. Thanks for boarding! Great tools!

**Comment by KrauseFx** [comment]
This is now resolved: https://boarding.herokuapp.com

Please follow the [update guide](https://github.com/fastlane/boarding/#update-to-a-new-version)

**Comment by fremontmj** [comment]
Worked.  Thanks!




I followed your recommended update directions.  I did have to resolve a bunch of git merges manually (warning: no common commits)...

**Comment by KrauseFx** [comment]
:+1:
